name: Robot Framework Tests 

on: push

jobs: 
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        pip install robotframework
        pip install robotframework-requests

    - name: Rodar os testes do Robot Framework
      run: robot -d results tests_company

    - name: Salvar resultado dos testes
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: ./results
