name: Robot Framework Tests 

on: push

jobs: 
  test:
    name: Run Tests
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://jessicacirne.github.io/Teste-de-API-com-Robot/report.html

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        pip install robotframework
        pip install robotframework-requests
        pip install robotframework-collections

    - name: Rodar os testes do Robot Framework
      run: robot -d results tests_company

    - name: Salvar resultado dos testes
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: ./results
        
    - name: Definir paginas
      uses: actions/configure@v2

    - name: Upload artefatos
      uses: actions/upload-pages-artifact@v1
      with: 
        path: results/

    - name: Deploy para Github Pages 
      id: deployment
      uses: actions/deploy-pages@v1